### ISSUE TITLE
TLS Certificate expired

### ISSUE THREAD

**Issue by robfotheringham** [decisiongrid/Issues#10]
Hi - I am trying to test my rule solver via a Postman call and I am getting a TLS certificate expired message. 

I have reset and change API key, but digging deeper it seems to be on the network side. Is there a std way around this?

Many thanks

**Comment by robfotheringham** [comment]
I should have added I can successfully call the API via javascript code from VS Code and can see that it works. I am attempting to connect to the API via another environment and was getting the certificate error so tried it in Postman and also hit the problem. Any help welcome.

**Comment by BakuE** [comment]
Hello Robfotheringham,

Thank you for reaching out.

We have tested out the rule solver based on your description above. It worked perfectly for us, we assume that the problem was on Heroku's side because we got a notification around the same time about the outage of their service.

We are supporting TLS v1.2 a TLS v1.3, but no other version.

Please try it again and let us know if it is working now.

Thank you.

Regards,
Erik

**Comment by robfotheringham** [comment]
Hi - No it is not working within Postman. Postman config says it supports TLS 1.2. Any ideas?

Cheers, 
Rob

Logs below:

POST https://api.decisionrules.io/rule/solve/038ce483-3985-16c6-1b5f-5251fdfa2a67/1: {
  "Error": "certificate has expired",
  "Request Headers": {
    "authorization": "Bearer FvC_CJFOXlwCtSjCnyBxRzUslK63xYgdgAxC9GauGKRwaSs23qIzCTU8G4cRvKZE",
    "content-type": "application/json"
  },
  "Request Body": "{\"data\": {\"Country\": \"UK\"}}"
}

**Comment by leosrehacek** [comment]
Hello Robfotheringham,

what version of Postman do you use?

It looks like it is problem with Postman.
Check for Postman updates.

If you have any questions please let me know.

Regards,
Leos
