### ISSUE TITLE
Limit to Bulk Solve?

### ISSUE THREAD

**Issue by DelphiData** [decisiongrid/Issues#17]
In the testing bench, i'm attempting a bulk solve that works with 5 or so, but when attempting thousands plus gives no output results. Is there a limit to data elements that can be used in with decision tree bulk solve in the test bench? Would the python API if functional allow for more bulk solve? Shows response 200 but with single output instead of nested array: Following is example of the output:
```
{
      "Guideline": {},
      "Guideline Grouping": {},
      "Anticipated Treatment/Diagnostics": {},
      "Body-Part": {},
      "ReportIDOut": {}
    }
```

There should be a nested array of thousands here.

**Comment by ten-petr** [comment]
Yes, there are general limits for SOLVER API:
- Request size must be lower or equal to 100MB otherwise it is dropped
- Whole request must finalize in 60s otherwise it is dropped
- Scripting rule and ruleflow applies execution time limits according your actual plan.

In case you need to make a lot of calculation, you have to split the request to chunks and call the Solver API multiple times. This is how the REST works in general, because it is synchronous. You can call the whole batch in parallel to achieve very fast execution which will use more CPU cores.


**Test bench bulk solve:**
Example with the default samplerule:
![image](https://user-images.githubusercontent.com/75977633/212328141-7880c997-2834-477a-be3b-fca49f36717d.png)

**Python SDK bulk solve:**
You can simply pass the array of JSON objects:
```
 request_body = [
    {
        "PrimarySite": "lung", "Character": {}, "SubLocation": {}, "Measure": "8", "Change": {}, "Age": "35", "Finding": "nodule", "ReportID": "8475"}, 
    {
        "PrimarySite": "lung", "Character": {}, "SubLocation": {}, "Measure": "8", "Change": {}, "Age": "35", "Finding": "nodule", "ReportID": "8475"
    }]
```

**Comment by DelphiData** [comment]
The json file shows to 2454KB. Would the request size be different? Even in small batches its timing out. Could be that the testing bench has lower capacity? I havent been able to get the python API to run without error yet or would attempt that route. 

```
import asyncio
import decisionrules


async def solve():
    solver = decisionrules.SolverApi("#SOLVER API KEY#")
    request_body = {"PrimarySite":"lung","Character":{},"SubLocation":{},"Measure":"8","Change":{},"Age":"35","Finding":"nodule","ReportID":"8475"}
    response = await solver.solve(decisionrules.SolverType.RULE, "#RULE ID#", request_body, "STANDARD", 1)
    print(response)
asyncio.run(solve())
```
Now getting:
```
RuntimeError                              Traceback (most recent call last)
C:\Users\JOEYBA~1\AppData\Local\Temp/ipykernel_54056/3967909454.py in <module>
      8     response = await solver.solve(decisionrules.SolverType.RULE, "#RULE ID#", request_body, "STANDARD", 1)
      9     print(response)
---> 10 asyncio.run(solve())

~\anaconda3\lib\asyncio\runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop
```

**Comment by ten-petr** [comment]
You have to enter your API KEY and RULE ID. I've anonymized your code because you've exposed your key in the previous posts.

**Comment by DelphiData** [comment]
Perfect thanks for you help. I've got going now!
