### ISSUE TITLE
Support for Arrays in response type

### ISSUE THREAD

**Issue by fpieper-diva-e** [decisiongrid/Issues#3]
We are currently facing a challenge with a number of different table rows that are supposed to map to the same field fo the output data model or add to it. Consider the following usecase:
A decision table that determines the client profitability / segment as in the sample rule provided by the platform. However, clients may be assigned to multiple segments. In this case, you have multiple options of configuring this on the platform:

- Configure a boolean field for each segment in the response type and set it accordingly
- Configure all possible combinations in the decsion table and set all segments in the response
- Configure multiple decision tables to match the individual rules per segment and query them from the client side individually

However, looking at a usecase with > 20 segments, this does not scale in any of the variants described above.

As such, it would be nice to have the option of configuring an array of values as the response type and add values to the array in the individual table rows that works as follows:

- In the response data model, add Array of values (Maybe String values as default)
- In the decision table Result field configure the corresponding field with an 'add to array' option.

What do you think? Any feedback on the usecase is greatly appreciated.

**Comment by BakuE** [comment]
Hello @fpieper-diva-e.

I am sorry for replying just now.

We appreciate your feedback and idea on how to improve DecisionRules.
You are right with the options which are at the moment available. To configure this kind of rule might be time-consuming and may cause an error because of the human errors at configuration.

I am redirecting your request/feedback to our development team, and we will consider implementing this feature into DecisionRules to make your work more efficient.  From my perspective, the second option you mentioned (In the decision table Result field configure the corresponding field with an 'add to array' option.) is the way how it should be done.

In case of any other questions/ideas/feedback, do not hesitate to contact me at erik.lehocky@decisionrules.io
Thank you,

Erik from DecisionRules

**Comment by leosrehacek** [comment]
Implemented
