### ISSUE TITLE
Can i use the Scripting Rules i created as Custom functions in the Decision Table's Table Designer?

### ISSUE THREAD

**Issue by withmanohar** [decisiongrid/Issues#6]

**Comment by BakuE** [comment]
Hello @withmanohar,

Thank you for your question.

Unfortunately, this functionality is not available in the DecisionRules application. The reason is that decision tables and scripting rules are two separate functions, so you can not reuse one rule in other.

The solution for your use case might be the new functionality we are currently working on that is called rule flow/rule chaining, this will be on production by the end of this month. Rule flow will allow you to connect more rules together and also to combine scripting rules with decision tables.

You can find more information about our roadmap/functionalities at [https://docs.decisionrules.io/docs/roadmap](url)

Thank you.

Regards,
Erik, DecisionRules team

**Comment by withmanohar** [comment]
Hi Erik,
Thanks for the quick response and inputs.

Regards,
Manohar
